[build]
  functions = "functions"
  # command = "npm run build"  # Uncomment if you have a build step

[build.environment]
  NODE_VERSION = "18"  # Adjust to your Node.js version if different

[functions]
  included_files = ["routes/**/*.js", "controllers/**/*.js"]
  node_bundler = "esbuild"  # Optional: specify the bundler if needed

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Uncomment the following if you need CORS headers
# [[headers]]
#   for = "/*"
#     [headers.values]
#     Access-Control-Allow-Origin = "*"
